// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Proceso.Infraestructura.Persistencia;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260330013540_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Proceso.Domain.Entities.Metric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CpuPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("cpu_percent");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("DiskPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("disk_percent");

                    b.Property<int>("DiskTotalGb")
                        .HasColumnType("integer")
                        .HasColumnName("disk_total_gb");

                    b.Property<int>("DiskUsedGb")
                        .HasColumnType("integer")
                        .HasColumnName("disk_used_gb");

                    b.Property<string>("Host")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("local")
                        .HasColumnName("host");

                    b.Property<decimal>("MemPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("mem_percent");

                    b.Property<int>("MemTotalMb")
                        .HasColumnType("integer")
                        .HasColumnName("mem_total_mb");

                    b.Property<int>("MemUsedMb")
                        .HasColumnType("integer")
                        .HasColumnName("mem_used_mb");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_metrics_created_at");

                    b.HasIndex("Host", "CreatedAt")
                        .HasDatabaseName("idx_metrics_host_created_at");

                    b.ToTable("metrics", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
